[package]
name = "scarydb"
version = "0.1.0"
edition = "2021"
default-run = "scarydb"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.5.0"
bson = "2.0"
serde_bytes = "0.11"
arrow = "4.0"
parquet = "4.0"
serde_yaml = "0.9"
base64 = "0.21"
csv = "1.1"
quick-xml = "0.30"
yaml_rust2 = "0.9"
tantivy = "0.14"
uuid = { version = "1.4", features = ["v4"] }
bcrypt = "0.13"
rustls = "0.22"
config = "0.14"
walkdir = "2.5"
glob = "0.3"
notify = "5.0"
anyhow = "1.0"
thiserror = "1.0"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"